on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      -name: "Login to Dokcer hub"
        run: docker login --username ahmedmandouh --password dckr_pat_woFKEBk-gYfXWZ-p5j1-unIuhdg


