on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username ahmedmandouh --password dckr_pat_BD7U4-7g2bwMAFwv1MqeMN9HGXQ


